CREATE TABLE customers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  account_number VARCHAR(20) NOT NULL UNIQUE,
  issue_date DATE NOT NULL,
  interest_rate DECIMAL(5,2) NOT NULL,
  tenure_months INT NOT NULL,
  emi_due DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
